# Generated by Django 6.0.5 on 2026-05-31 15:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama Kategori')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='📁', help_text='Gunakan emoji sebagai ikon kategori', max_length=10, verbose_name='Ikon (emoji)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Deskripsi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Subjek')),
                ('message', models.TextField(verbose_name='Pesan')),
                ('is_read', models.BooleanField(default=False, verbose_name='Sudah Dibaca')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dikirim')),
            ],
            options={
                'verbose_name': 'Pesan Kontak',
                'verbose_name_plural': 'Pesan Kontak',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Judul')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(help_text='Ringkasan singkat artikel (maks 500 karakter)', max_length=500, verbose_name='Ringkasan')),
                ('content', models.TextField(verbose_name='Konten')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/', verbose_name='Gambar')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Diterbitkan')], default='draft', max_length=10, verbose_name='Status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Artikel Unggulan')),
                ('author', models.CharField(default='Admin', max_length=100, verbose_name='Penulis')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Dilihat')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Publikasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diperbarui')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
                'ordering': ['-published_at'],
            },
        ),
    ]
